---
program_config:



...

---

slave_name: somanet_node

slave_count: 3

slave_type: driver

slave_tags:
  - right_motor
  - left_motor
  - lifter_motor

alias: 0

position: 1
 
vendor_id: 0x10

product_code: 0x11
 
domain_name: wheel_domain

#dc_config:
#  assign_activate: 0
#  sync0_activate: 0
#  sync0_shift: 0
#  sync1_activate: 0
#  sync1_shift: 0

sync_manager_config:
  -
    index: 0
    direction: input
    watchdog_mode: disabled
  -
    index: 1
    direction: output
    watchdog_mode: disabled
  -
    index: 2
    direction: input
    watchdog_mode: disabled
  -
    index: 3
    direction: output
    watchdog_mode: disabled

pdo_mapping_1:
 addr: 0x1600
 type: rx

 pdos:
  -
      name: a
      index: 0
      subindex: 0
      bitlength: 16
      type: e
  -
    name: a
    index: 0
    subindex: 0
    bitlength: 16
    type: e

pdo_mapping_2:
 addr: 0x1a00
 type: tx

 pdos:
  -
      name: a
      index: 0
      subindex: 0
      bitlength: 16
      type: e
  -
    name: a
    index: 0
    subindex: 0
    bitlength: 16
    type: e

...